services:
  mosquitto_broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - mqtt_network

  publicador:
    build: ./publicador
    container_name: mqtt_publicador
    depends_on:
      - mosquitto_broker
    networks:
      - mqtt_network

  suscriptor:
    build: ./suscriptor
    container_name: mqtt_suscriptor
    depends_on:
      - mosquitto_broker
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge

