services:
  mosquitto_broker:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/certs:/mosquitto/certs
    networks:
      - mqtt_network

  publicador:
    build: ./publicador
    container_name: mqtt_publicador
    depends_on:
      - mosquitto_broker
    networks:
      - mqtt_network
    volumes:
      - ./mosquitto/config/certs:/app/certs

  suscriptor:
    build: ./suscriptor
    container_name: mqtt_suscriptor
    depends_on:
      - mosquitto_broker
    networks:
      - mqtt_network
    volumes:
      - ./mosquitto/config/certs:/app/certs

networks:
  mqtt_network:
    driver: bridge

